package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/permanu/docksmith"
)

func runInit(_ config, args []string) {
	dir := targetDir(args)

	fw, err := docksmith.Detect(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	content := buildTOMLTemplate(fw)

	outPath, err := writeProjectFile(dir, "docksmith.toml", []byte(content), 0o644, false)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			path, pathErr := projectFilePath(dir, "docksmith.toml")
			if pathErr != nil {
				fmt.Fprintf(os.Stderr, "error: %v\n", pathErr)
				os.Exit(1)
			}
			fmt.Fprintf(os.Stderr, "error: docksmith.toml already exists at %s\n", path)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "error: write docksmith.toml: %v\n", err)
		os.Exit(2)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", outPath)
}

// buildTOMLTemplate generates a commented docksmith.toml pre-filled with
// values inferred from the detected framework.
func buildTOMLTemplate(fw *docksmith.Framework) string {
	runtime := frameworkToRuntime(fw.Name)
	version := frameworkVersion(fw)
	build := fw.BuildCommand
	start := fw.StartCommand
	port := fw.Port

	// Fall back to defaults when detection didn't populate commands.
	if build == "" || start == "" {
		db, ds := docksmith.FrameworkDefaults(fw.Name)
		if build == "" {
			build = db
		}
		if start == "" {
			start = ds
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by docksmith. Customize as needed.\n")
	b.WriteString("# See: https://github.com/permanu/docksmith\n\n")

	writeTOMLLine(&b, "runtime", runtime)
	writeTOMLLine(&b, "version", version)
	writeTOMLLine(&b, "build", build)
	writeTOMLLine(&b, "start", start)
	if port > 0 {
		writeTOMLLine(&b, "port", fmt.Sprintf("%d", port))
	} else {
		writeTOMLLine(&b, "port", "8080")
	}

	return b.String()
}

func writeTOMLLine(b *strings.Builder, key, val string) {
	if val == "" {
		fmt.Fprintf(b, "# %s = \"\"\n", key)
		return
	}
	// Port is an integer; don't quote it.
	if key == "port" {
		fmt.Fprintf(b, "# %s = %s\n", key, val)
		return
	}
	fmt.Fprintf(b, "# %s = %q\n", key, val)
}

// frameworkToRuntime maps the Framework.Name to the canonical runtime
// identifier used in docksmith.toml.
func frameworkToRuntime(name string) string {
	switch {
	case name == "bun" || name == "bun-elysia" || name == "bun-hono":
		return "bun"
	case name == "deno" || name == "deno-fresh" || name == "deno-oak":
		return "deno"
	case name == "nextjs" || name == "nuxt" || name == "sveltekit" || name == "astro" ||
		name == "remix" || name == "gatsby" || name == "vite" || name == "create-react-app" ||
		name == "angular" || name == "vue-cli" || name == "solidstart" ||
		name == "nestjs" || name == "express" || name == "fastify":
		return "node"
	case name == "django" || name == "fastapi" || name == "flask":
		return "python"
	case name == "go" || name == "go-gin" || name == "go-echo" || name == "go-fiber" ||
		name == "go-std" || name == "go-chi":
		return "go"
	case name == "rails" || name == "sinatra":
		return "ruby"
	case name == "laravel" || name == "wordpress" || name == "symfony" || name == "slim" || name == "php":
		return "php"
	case name == "spring-boot" || name == "quarkus" || name == "micronaut" || name == "maven" || name == "gradle":
		return "java"
	case name == "aspnet-core" || name == "blazor" || name == "dotnet-worker":
		return "dotnet"
	case name == "rust" || name == "rust-generic" || name == "rust-actix" || name == "rust-axum":
		return "rust"
	case name == "elixir-phoenix":
		return "elixir"
	case name == "static":
		return "static"
	default:
		return name
	}
}

// frameworkVersion extracts the most appropriate version string from the
// detected framework.
func frameworkVersion(fw *docksmith.Framework) string {
	switch {
	case fw.NodeVersion != "":
		return fw.NodeVersion
	case fw.PythonVersion != "":
		return fw.PythonVersion
	case fw.GoVersion != "":
		return fw.GoVersion
	case fw.PHPVersion != "":
		return fw.PHPVersion
	case fw.JavaVersion != "":
		return fw.JavaVersion
	case fw.DotnetVersion != "":
		return fw.DotnetVersion
	case fw.BunVersion != "":
		return fw.BunVersion
	case fw.DenoVersion != "":
		return fw.DenoVersion
	default:
		return ""
	}
}

func projectFilePath(dir, name string) (string, error) {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("resolve target dir: %w", err)
	}
	joined := filepath.Join(absDir, name)
	cleaned := filepath.Clean(joined)
	if !strings.HasPrefix(cleaned, absDir+string(filepath.Separator)) && cleaned != absDir {
		return "", fmt.Errorf("path %q escapes project directory", name)
	}
	return cleaned, nil
}

func writeProjectFile(dir, name string, data []byte, perm os.FileMode, overwrite bool) (string, error) {
	path, err := projectFilePath(dir, name)
	if err != nil {
		return "", err
	}

	// Reject symlinks — prevents writing through a symlink to an outside file.
	if info, err := os.Lstat(path); err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("path %q is a symlink", path)
		}
		if !overwrite {
			return path, os.ErrExist
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return "", err
	}
	return path, nil
}
